// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdfsdylxylzsvmrapusb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkZnNkeWx4eWx6c3ZtcmFwdXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjA0MzAsImV4cCI6MjA3MjQ5NjQzMH0.X_lBAVPWSV1ufE-4o5S1x-uCsQgLBNkd_AC_5-bvSQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});